version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4321:4321"
    volumes:
      - ./public:/usr/share/nginx/html:ro
    environment:
      - NODE_ENV=production